apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
      openshift.io/image.dockerRepositoryCheck: "2023-05-15T20:38:11Z"
    creationTimestamp: "2023-05-15T20:38:11Z"
    generation: 2
    labels:
      app: scale
      app.kubernetes.io/component: scale
      app.kubernetes.io/instance: scale
    managedFields:
    - apiVersion: image.openshift.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:openshift.io/generated-by: {}
          f:labels:
            .: {}
            f:app: {}
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/instance: {}
        f:spec:
          f:tags:
            .: {}
            k:{"name":"latest"}:
              .: {}
              f:annotations:
                .: {}
                f:openshift.io/imported-from: {}
              f:from: {}
              f:generation: {}
              f:importPolicy:
                .: {}
                f:importMode: {}
              f:name: {}
              f:referencePolicy:
                .: {}
                f:type: {}
      manager: oc
      operation: Update
      time: "2023-05-15T20:38:11Z"
    name: scale
    namespace: chapter6
    resourceVersion: "2368606"
    uid: 0d00c9ee-a220-4fbb-91de-744f93584265
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: quay.io/redhattraining/exoplanets
      from:
        kind: DockerImage
        name: quay.io/redhattraining/exoplanets
      generation: 2
      importPolicy:
        importMode: Legacy
      name: latest
      referencePolicy:
        type: Source
  status:
    dockerImageRepository: image-registry.openshift-image-registry.svc:5000/chapter6/scale
    publicDockerImageRepository: default-route-openshift-image-registry.apps-crc.testing/chapter6/scale
    tags:
    - items:
      - created: "2023-05-15T20:38:11Z"
        dockerImageReference: quay.io/redhattraining/exoplanets@sha256:5d03eb02ed27d4530e5540cc85afd982616ec25e9a7ee8c8b72d4381eeea2738
        generation: 2
        image: sha256:5d03eb02ed27d4530e5540cc85afd982616ec25e9a7ee8c8b72d4381eeea2738
      tag: latest
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: "2023-05-15T20:38:11Z"
    labels:
      app: scale
      app.kubernetes.io/component: scale
      app.kubernetes.io/instance: scale
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:openshift.io/generated-by: {}
          f:labels:
            .: {}
            f:app: {}
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/instance: {}
        f:spec:
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":8080,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: oc
      operation: Update
      time: "2023-05-15T20:38:11Z"
    name: scale
    namespace: chapter6
    resourceVersion: "2368607"
    uid: 79059699-6990-4bbb-b8cd-81e2c9c4b4bd
  spec:
    clusterIP: 10.217.4.143
    clusterIPs:
    - 10.217.4.143
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deployment: scale
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
